/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "You don't like walls, never did. You might even say their your archenemies. You not sure why exactly, they haven't done anything specifically wrong, but it doesn't matter. This wall must go, even it means you have to punch it to bits by yourself.": "你不喜欢墙壁，从来没有。你甚至可以说他们是你的宿敌。你不知道确切的原因，他们没有做任何特别错误的事情，但这无关紧要。这堵墙必须拆除，即使这意味着你必须自己把它打成碎片。",
    "Airstrike Caller": "空袭来电者",
    "Airstrike Caller damage:": "空袭呼叫者伤害：",
    "Bulldozer": "推土机",
    "Bulldozer damage:": "推土机伤害：",
    "Cash": "现金",
    "Close": "关闭",
    "Clubber": "挥棍者",
    "Clubber damage:": "挥棍者伤害：",
    "Damage": "损害",
    "Destroy Wall": "摧毁墙壁",
    "Grenademan": "榴弹兵",
    "Grenademan damage:": "手榴弹伤害：",
    "Gunshooter": "枪手",
    "Gunshooter damage:": "枪手伤害：",
    "Hand damage:": "手部伤害：",
    "Hello there, welcome to Wall Destroyer:Rewritten, this is a modern rewrite of the original Wall Destroyer by Tellurium. I hope you have fun and tell me about your experience with this game so that it may improve.": "您好，欢迎来到 墙壁破坏者：重制版，这是 Tellurium 对原始 墙壁破坏者 的现代重写。 我希望你玩得开心，并告诉我你对这个游戏的体验，以便它可以改进。",
    "Needs:": "需求：",
    "Overall damage:": "综合伤害：",
    "Punch Wall": "用拳头砸墙",
    "Puncher": "拳击手",
    "Puncher damage:": "拳击手伤害：",
    "Stats": "统计数据",
    "Swordsman": "剑士",
    "Swordsman damage:": "剑士伤害：",
    "Upgrades": "升级",
    "Welcome": "欢迎",
    "What's this Wall?": "这是什么墙？",
    "Wrecking Ball": "破碎球",
    "Wrecking Ball damage:": "破坏球伤害：",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "A man with grenades. I am a master of descriptions.": "一个手持手榴弹的人。我是一个描写大师。",
    "Awards": "奖励",
    "base damage.": "基础伤害。",
    "bricks.": "砖块。",
    "cash.": "现金。",
    "cosmic knowledge.": "宇宙知识。",
    "Destroy the wall and move on to a bigger one.": "摧毁这堵墙，换一堵更大的墙。",
    "Does": "造成",
    "Gives": "给予",
    "Heavy duty Building": "重型建筑",
    "Melee Building": "近战建筑",
    "Rams the wall. So good.": "撞墙吧。 太好了。",
    "Ranged Building": "远程建筑",
    "Shoots his gun.": "射击他的枪。",
    "Some question the use of swords on a brick wall. Those guys are lame.": "有些人质疑在砖墙上使用剑。 那些家伙很蹩脚。",
    "Something actually meant for destroying walls.": "实际上是用来摧毁墙壁的东西。",
    "Worth": "价值",
    "You know, the guy that calls airstrikes.": "你知道的，那个叫空袭的家伙。",
    "Damage the wall.": "损坏墙壁。",
    "Overnab": "覆盖",
    "Not to be confused with the other kind of clubbing.": "不要与其他类型的泡吧相混淆。",
    "A little padding.": "一点衬垫。",
    "Costs": "成本",
    "damage by hand.": "手造成的伤害。",
    "damage to the wall.": "对墙壁的伤害。",
    "Deal": "成交",
    "Game Saved": "游戏已保存",
    "Gloves": "手套",
    "Hand punches do": "拳打脚踢",
    "Helpers": "助手",
    "Hire": "雇佣",
    "Hired Help": "雇佣的帮手",
    "more damage.": "更多伤害。",
    "more damage. Punchers do": "更多伤害。拳击手造成的",
    "puncher.": "拳击手。",
    "Now that you've got your first companion you might want to do some research to improve everyones wall destroying capabilities. So you start the RUC~Realistic Upgrades Corporation, \"A good name\"- you tell yourself.": "现在您有了第一个伙伴，您可能想做一些研究来提高每个人的墙壁破坏能力。 所以你创办了 RUC~现实升级公司，“一个好名字”——你告诉自己。",
    "Punches the wall for you": "为了你击打墙壁",
    "Scrub": "擦洗",
    "You realize that this might take a while to do by yourself, maybe you should hire some people to help you? Like-minded brothers in arms who despise walls just like you. You just need to pay them a bit to quit their current job and join you.": "你意识到这可能需要一段时间才能自己完成，也许你应该雇一些人来帮助你？ 和你一样鄙视墙壁的志同道合的战友。 您只需要付给他们一点钱就可以辞掉他们目前的工作并加入您的行列。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) trillion$/,
    /^([\d\.]+) thousand$/,
    /^([\d\.]+) billion$/,
    /^([\d\.]+) million$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);